### ISSUE TITLE
Is this you?

### ISSUE THREAD

**Issue by DevBadger10** [senseiwells/ServerReplay#1]
https://modrinth.com/mod/server-side-replay-recorder I found this, is this hosted by you? Cause I wanna use this mod, but I can't compile it myself for reasons (I know how to but the hosting I'm using doesn't support custom mods)

**Comment by senseiwells** [comment]
This is not my mod

**Comment by thecolonel63** [comment]
> https://modrinth.com/mod/server-side-replay-recorder I found this, is this hosted by you? Cause I wanna use this mod, but I can't compile it myself for reasons (I know how to but the hosting I'm using doesn't support custom mods)

ssrr is actually my mod - I can't help you with getting it working on a host that doesn't support custom mods though.
