### ISSUE TITLE
Server crashed while starting

### ISSUE THREAD

**Issue by MinecraftPEayer** [senseiwells/ServerReplay#11]
The server crashed after I installed this mod
Attached is an error message
[log.txt](https://github.com/senseiwells/ServerReplay/files/14398949/log.txt)

Minecraft version: 1.20.2
Fabric Loader version: 0.14.24

Mod list:
AppleSkin 1.20.2-2.5.1
Carpet Extra 1.20.2-1.4.118
Fabric API 0.91.1+1.20.2
Carpet 1.20.2-1.4.121-v231011
Fabric Language Kotlin 1.10.18+kotlin. 1.9.22
Lithium 1.20.2-0.12.0
Proxy Protocol Support 1.0.3
Servux 1.20.2-0.1.0
Spark 1.10.54
Syncmatica 1.20.2-0.3.11
TabTPS 1.20.2-1.3.21

**Comment by senseiwells** [comment]
Please update your fabric loader, let me know if the issue persists

**Comment by MinecraftPEayer** [comment]
Thanks, the problem is solved

**Comment by MinecraftPEayer** [comment]
umm
i got a new problem

when i started player replay record
I will be disconnected from the server shortly

![image](https://github.com/senseiwells/ServerReplay/assets/87757022/31915bf3-86f7-4d6c-bbd5-445d85e1602f)
