### ISSUE TITLE
Question: Using both ReplayMod and ServerReplay together?

### ISSUE THREAD

**Issue by MightyKnight** [senseiwells/ServerReplay#18]
Hi,
can this be installed alongside the usual ReplayMod?

I'm specifically talking about the situation where I would play a singleplayer world and share it to LAN (the LAN world in Minecraft runs as an integrated server).
Will there be any interference between ServerReplay and Replaymod or will these work together?

**Comment by senseiwells** [comment]
You don't even need to share it to LAN. It should work out of the box. You can also change the recording directory to be the replay client directory so you don't have to move files around.

I haven't actually tested it but there shouldn't be any issues, if there are please report them here - it is a bug and I will fix it.
