### ISSUE TITLE
Any plan for 1.19.2?

### ISSUE THREAD

**Issue by MICOAST** [senseiwells/ServerReplay#20]
1.19.2 as a major release for 1.19.x, hopefully there are plans for 1.19.2,thanks!

**Comment by senseiwells** [comment]
No, unfortunately I will not be supporting 1.19.2. I am only supporting the **latest** minor version for every major version with the exception of the **latest** major version where I will support all minor versions until the next major version releases.

The plan is to support `1.17.1`, `1.18.2`, `1.19.4`, `1.20.1`, `1.20.2`, `1.20.4`, `1.20.5` until `1.21` comes out where I will likely stop supporting `1.20.1`, `1.20.2`, and `1.20.4`.

Just out of curiosity, is there any specific reason you do not want to update to `1.19.4`?

**Comment by MICOAST** [comment]
Eumm,just many mods update 1.19.2 and skip other versions of 1.19.x
