### ISSUE TITLE
Frozen players in replay mods

### ISSUE THREAD

**Issue by karrebri000** [senseiwells/ServerReplay#24]
I was setting up the server side replay mod and I got it to work where it will record all players all the time but the issue is when I view the replays after they were recorded I noticed no players move in the replays I am guessing this is because of a Mod incompatibility to do with networking but I have no Idea what mod it might be. It is very odd I was moving around in the replay but it isn't captured but particles appear beneath me at certain points. I have tried making many replay mods and keep having the same issue and yes both the server and the client replay mod are in the same version 1.20.4. Here is a list of the Mods.
![Screenshot 2024-04-05 011035](https://github.com/senseiwells/ServerReplay/assets/54506882/88677186-17eb-4772-b8b8-d71ff0d2b41c)
![Screenshot 2024-04-05 011144](https://github.com/senseiwells/ServerReplay/assets/54506882/51eb4102-f9d6-4068-b693-d4314cbdbb2a)

**Comment by karrebri000** [comment]
I must add that I did get these files off the server and upload them to drive to use them on my main PC I don't think that would be a problem unless I am not aware of drive messing with the replay mod files and breaking them.

**Comment by senseiwells** [comment]
Could you please uninstall all unnecessary mods and add them back one by one to see which is the one causing issues?
I would think it's likely ViaFabric or the other Via mods, badpackets, or very many players. So you can try these first.

Also ServerReplay 1.0.8 is released. Please also update to this version.

**Comment by Timongcraft** [comment]
For me this behavior occurs when using https://modrinth.com/mod/vmp-fabric but I don't think that can be fixed easily.
