### ISSUE TITLE
Feature Request: Record Multiple Players

### ISSUE THREAD

**Issue by Timongcraft** [senseiwells/ServerReplay#27]
It would be great if you could record multiple players in a single replay file or if you could merge player replays to one file using a command.

**Comment by senseiwells** [comment]
You can already record multiple players in a single replay file by using chunk replays.

Merging player replays is simply not possible. The largest problem is the issue of players being in different dimensions. 
The client cannot be sent data for multiple dimensions all at once, it's simply not possible.
Apart from that there are still loads of smaller issues, like how to deal with conflicts. It's possible that different information is sent to different players, e.g. bossbars, scoreboards, chat messages. How do you decided which ones to display?

**Comment by Timongcraft** [comment]
> You can already record multiple players in a single replay file by using chunk replays.
> 
> Merging player replays is simply not possible. The largest problem is the issue of players being in different dimensions. The client cannot be sent data for multiple dimensions all at once, it's simply not possible. Apart from that there are still loads of smaller issues, like how to deal with conflicts. It's possible that different information is sent to different players, e.g. bossbars, scoreboards, chat messages. How do you decided which ones to display?

Yea but the chunk thing also has the downside I can't jsut tell it to record the whole overworld and it will record the chunks that are loaded by players it will just try to load everything and crash the server.

**Comment by senseiwells** [comment]
Yeah, that's intended, the idea is to initially load all the chunks and then never touch chunkloading again - this drastically helps with file size as you're not constantly loading and unloading chunks.

I could add a config that makes it so the chunks are *not* loaded when the recording starts but instead only when they are actually loaded. You can make a separate feature request for that if you wish.
