### ISSUE TITLE
Feature Request: Add config to not load chunks when a chunk-recording is started

### ISSUE THREAD

**Issue by Timongcraft** [senseiwells/ServerReplay#28]
Add a config value which makes it so the chunks are not loaded when the recording starts but instead only when they are actually loaded.
(Maybe also add a config option to just record a whole dimension and not specific chunk ranges)

**Comment by senseiwells** [comment]
This is in the newest ServerReplay version which you can download on modrinth!
https://modrinth.com/mod/server-replay
