### ISSUE TITLE
Feature request: Paper/Spigot support

### ISSUE THREAD

**Issue by maxiwee69** [senseiwells/ServerReplay#31]
Support for Spigot/Bukkit or whatever you want to call it(i know different things but you know what i mean)

**Comment by senseiwells** [comment]
I will not support Bukkit/Spigot/Paper.

- There are the technical limitations of these server softwares. ServerReplay is a pretty complicated mod and requires Mixins which these softwares do not support.
- I would complicated the development process of ServerReplay - supporting multiple platforms is a pain and I do not have the time to do this, nor do I want to. For this reason I will also not be supporting Forge, or other mod loaders too.

**Comment by maxiwee69** [comment]
ah ok, :sadge:

**Comment by laoliuhhh** [comment]
you can try iseeyou[https://github.com/MC-XiaoHei/ISeeYou]

**Comment by TheIcemanZane** [comment]
> you can try iseeyou[https://github.com/MC-XiaoHei/ISeeYou]

God bless you for writing that, I've been looking for something like that for months and that is exactly what I needed
