### ISSUE TITLE
Compatibility w/ ViaVersion

### ISSUE THREAD

**Issue by joecooldoo** [senseiwells/ServerReplay#33]
I am running a Minecraft server with version 1.20.4 and would like the ability for newer/older clients to join my server. With ViaFabric installed (I am running a Fabric server), I can do just that. I added ServerReplay to monitor the server for various reasons (help with random mod problems on the server, make sure people aren't cheating), but on server startup, ViaFabric stops working and fails to start properly.

The ViaFabric error can be seen here:
https://mclo.gs/DzCfsvS

ServerReplay does not seem to produce any errors.
When I remove ServerReplay, ViaFabric begins to operate normally.

**Comment by FangFang66** [comment]
我也是这个问题，请问怎么才可以解决

**Comment by senseiwells** [comment]
This version should fix your issue: https://filebin.net/5jdy2xi73eh48e43/ServerReplay-1.0.8_mc1.20.4.jar
