### ISSUE TITLE
Where is the output file?

### ISSUE THREAD

**Issue by Link98745** [senseiwells/ServerReplay#4]
It says Build Successful and I don't know where the output file is

**Comment by Link98745** [comment]
And apparently it doesn't work with Geyser mc installed

**Comment by Link98745** [comment]
So Nevermind, but can you please make a how to build guide thing with another readme or something

**Comment by senseiwells** [comment]
The mod is currently very experimental and has lots of bugs that I am still working out. For this reason the mod is **not** released yet. If you know how to compile and install the mod yourself but I will not release the mod until I believe it to be stable.
