### ISSUE TITLE
Block automatic recording is not effective

### ISSUE THREAD

**Issue by KonnoYuuki06** [senseiwells/ServerReplay#42]
Server game version 1.20.1
ServerReplay config：

{
  "enabled": true,
  "world_name": "World",
  "server_name": "Server",
  "chunk_recording_path": ".\\recordings\\chunks",
  "player_recording_path": ".\\recordings\\players",
  "max_file_size": "0GB",
  "restart_after_max_file_size": false,
  "max_duration": "1d 6h",
  "restart_after_max_duration": true,
  "recover_unsaved_replays": true,
  "include_compressed_in_status": true,
  "fixed_daylight_cycle": -1,
  "chunk_recorder_load_radius": -1,
  "pause_unloaded_chunks": false,
  "pause_notify_players": true,
  "notify_admins_of_status": true,
  "fix_carpet_bot_view_distance": false,
  "ignore_sound_packets": false,
  "ignore_light_packets": true,
  "ignore_chat_packets": false,
  "ignore_scoreboard_packets": false,
  "optimize_explosion_packets": true,
  "optimize_entity_packets": false,
  "record_voice_chat": false,
  "replay_viewer_pack_ip": null,
  "replay_viewer_pack_port": 24464,
  "player_predicate": {
    "type": "has_uuid",
    "uuids": [
      "f39befef-4459-4110-8cec-8cf7ffa0b4d3",
      "7bf225df-e1c4-44e4-a9e8-e6ab99a99f12",
      "5a5399db-39ac-4936-9f79-4707a2c76eac"
    ]
  },
  "chunks": [
    {
      "name": "end",
      "dimension": "minecraft:the_end",
      "from_x": -51,
      "from_z": -39,
      "to_x": 52,
      "to_z": 38
    }
  ]
}

**Comment by senseiwells** [comment]
Your chunk area that you've specified is too small to be rendered by the client. Please refer to the README: https://github.com/senseiwells/ServerReplay?tab=readme-ov-file#chunks
