### ISSUE TITLE
How can I render the recorded file to a mp4 server-side?

### ISSUE THREAD

**Issue by huangdi95** [senseiwells/ServerReplay#45]
Hi, thanks for this great tool and this is exactly what I need!

I want to record first-person point-of-view Minecraft videos for all players on different servers. My question is, how can I render these first-person videos to mp4 server-side with this tool so that I can get videos automatically? Otherwise, I need to load mcpr files and render these videos one by one.

Thanks!

**Comment by senseiwells** [comment]
This is not a planned feature unfortunately, it would be extremely complicated and difficult to implement well.
