### ISSUE TITLE
Recording voicechat does not work

### ISSUE THREAD

**Issue by Serverator** [senseiwells/ServerReplay#47]
## Problem
When recording server replays, it does not record (or at least playback) the voicechat. Because of #48 I copied server replays in the minecraft `replay_recordings` to view them.
Recording on client with Replay Mod and Replay Voice Chat works perfectly.

## What I tried
I tested with both server and chunk recordings, both on online and offline server.

## Versions
Minecraft - 1.21
Replay Mod - 2.6.17
Replay Voice Chat - 1.3.8
Server Replay - 1.1.1

## Replay Files
Here are both client and server recordings, in case you want them
[recordings.zip](https://github.com/user-attachments/files/16482794/recordings.zip)

-----

If there are any way to restore lost audio from the server recording it would be greatly appreciated <3

**Comment by senseiwells** [comment]
This was intentional - see the [changelog](https://modrinth.com/mod/server-replay/version/1.1.1+mc1.21) of the version you downloaded, I updated ServerReplay before voicechat had updated. This feature will be added as the mod has been updated.
There is no way to recover lost audio because there was no way to record it as replay voicechat had not been updated.

**Comment by Serverator** [comment]
Fair enough, thank you!

**Comment by CrushedAsian255** [comment]
> This feature will be added as the mod has been updated.

Just wondering, is there a rough time frame for when the mod will be updated? No problem if there isn't. Thanks for the work on this mod, I really like the mod.

**Comment by senseiwells** [comment]
There's no timeline, it's just whenever I get around to it, unfortunately I have other priorities at the moment, this is just my hobby really, hopefully I'll have it done within a couple weeks.

**Comment by CrushedAsian255** [comment]
> There's no timeline, it's just whenever I get around to it, unfortunately I have other priorities at the moment, this is just my hobby really, hopefully I'll have it done within a couple weeks.

No problem :)
