### ISSUE TITLE
Carpet bot Doesent record more than 2 chunks

### ISSUE THREAD

**Issue by PeHeReBe** [senseiwells/ServerReplay#49]
I had hart time going into config and changing fix_carpet_bot setting becase it always reset itself. now i got it and the recording ony show players in 2x2 chunks and after that they dissapare. idk why i can see partickles from blocks placed/destroyed in the replay outside of the 2x2 chunks but nether the player ore the blocks beeing rendered in the replay.

sry for my english

**Comment by senseiwells** [comment]
Can you be more specific:
- Provide the Minecraft version and server replay version you are using.
- Provide the replay file that you are referencing.
- Provide steps to reproduce?

**Comment by PeHeReBe** [comment]
jep sry for late replay was on holidays.

mc server fabric: Minecraft 1.21 with Fabric Loader 0.15.11, mod: ServerReplay-1.1.1+mc1.21.jar.

Replay file: [Test.zip](https://github.com/user-attachments/files/16737385/Test.zip) (particles from destroyed block are visible at any location)

start recording for carpet bot -> stop recording
[config.json](https://github.com/user-attachments/files/16737388/config.json)

**Comment by senseiwells** [comment]
This has already been fixed in the latest version which you can download on modrinth
