### ISSUE TITLE
ServerReplay 1.1.2 for 1.20.4 Please

### ISSUE THREAD

**Issue by Redapple-one** [senseiwells/ServerReplay#51]
Our Minecraft Server Version still is 1.20.4
Because many of the mods we need are not available on 1.20.6

**Comment by Redapple-one** [comment]
e.g. https://modrinth.com/mod/carpet-tctc-addition and https://modrinth.com/mod/carpet-fixes

**Comment by senseiwells** [comment]
You can find the updated mod [here](https://modrinth.com/mod/server-replay/version/1.1.2+mc1.20.4).

For future reference, I will only support the latest minor version of each major version of the game, apart from the most recent major update where I will try to maintain all of the minor versions.

It's simply not feasible for me to maintain every minor version - it's not difficult to back-port just time consuming, so if you require future features/bug fixes you'll need to back-port it.

This will be the final version for 1.20.4 that I will release.

**Comment by PeterFujiyu** [comment]
谢谢，但是我已经为该服务器完成移植和修复，但仍然感谢您提供了移植。

**Comment by PeterFujiyu** [comment]
Thank you, but I have already ported and repaired the server, but thank you for providing the port.

**Comment by Redapple-one** [comment]
> You can find the updated mod [here](https://modrinth.com/mod/server-replay/version/1.1.2+mc1.20.4).
> 
> For future reference, I will only support the latest minor version of each major version of the game, apart from the most recent major update where I will try to maintain all of the minor versions.
> 
> It's simply not feasible for me to maintain every minor version - it's not difficult to back-port just time consuming, so if you require future features/bug fixes you'll need to back-port it.
> 
> This will be the final version for 1.20.4 that I will release.

Thank you very much!
