### ISSUE TITLE
Feature Request: Jump to ticks

### ISSUE THREAD

**Issue by copyandexecute** [senseiwells/ServerReplay#55]
Is it possible to add a feature where you can jump to a specific tick/timestamp?

**Comment by copyandexecute** [comment]
Oooh I've seen that something similar exists 
![grafik](https://github.com/user-attachments/assets/33824e07-da21-4c32-91b3-85e816e65668)
but I can't get it working

**Comment by copyandexecute** [comment]
I guess you have to set markers right?

**Comment by senseiwells** [comment]
Yes, this is a planned feature

**Comment by senseiwells** [comment]
Implemented in 6ab06918766e86d18c32a31f54e04a1d21fe93f1
