### ISSUE TITLE
Feature Request: Bypass Packet List

### ISSUE THREAD

**Issue by copyandexecute** [senseiwells/ServerReplay#56]
Could you add a feature to add a list of packets you dont want to include? E.g. i only want to record player movement so I'd like to disable specific packets like Chunk Blocks etc

**Comment by senseiwells** [comment]
All the reasonable packets you wouldn't want to include are already available to toggle in the config.
If you disable chunk packets your replay will simply not render...

**Comment by copyandexecute** [comment]
oh, so can I decrease the chunk distance for a player recording?

**Comment by senseiwells** [comment]
No, I don't plan on anything like this since it's use case is so niche.
It sort of sounds like this mod is not what you want if you only want to record player movement.

**Comment by copyandexecute** [comment]
No problem, the mod is really well made! thanks
