### ISSUE TITLE
Cannot record simple voice chat

### ISSUE THREAD

**Issue by PeterTerpe** [senseiwells/ServerReplay#61]
Replay has no voice, after "record_voice_chat" was set to true.
Client has replay-voice-chat installed, and has no problem recording and playing voices in single-player replay recordings.

server replay version: 1.1.1+mc1.21
simple voice chat version: 1.21-2.5.18
replay voice chat version: 1.21-1.3.8
fabric loader verison: 0.15.11

**Comment by senseiwells** [comment]
Please update ServerReplay. See #47
