### ISSUE TITLE
Incompatibility with Servux

### ISSUE THREAD

**Issue by mcbianxiao** [senseiwells/ServerReplay#63]
When I installed Servux and ServerReplay on my MinecraftServer, I found that this caused the MiniHUD to not display the structure properly. When I removed ServerReplay, everything worked fine.

Minecraft Version: 1.21
ServerReplay Version: 1.1.1+mc1.21
Fabric Loader: 0.16.0
Servux Version: 1.21-0.3.6 by https://github.com/sakura-ryoko/servux
MiniHUD Version: 1.21-0.31.999-sakura.14 by https://github.com/sakura-ryoko/minihud

**Comment by senseiwells** [comment]
Yeah, related to #23, the mod developer's packet implementation is flawed causing errors whenever other mods try to write their packets. Really this should be fixed in Servux but I will add another exception for this.
