### ISSUE TITLE
Option to not include server resource pack in every recording

### ISSUE THREAD

**Issue by HoldYourWaffle** [senseiwells/ServerReplay#65]
I just noticed that every recording contains a copy of the server resource pack. I assume this makes an accurate replay easier, but with a non-trivially sized resource pack this takes up too much storage for my poor server T_T

It'd be great if there was a config option to disable this behavior. It might be nice to still include some kind of marker of which resource pack was used, e.g. the SHA1 of server.properties.

**Comment by senseiwells** [comment]
This is how replay mod records resource packs. I can add an option to disable this but then there's no guarantee that the resource pack will work in the replay

**Comment by HoldYourWaffle** [comment]
That'd be amazing! In the words of a not-so-wise man(child):
![A sacrifice... I'm willing to make.](https://media1.tenor.com/m/4taYWFg1U6AAAAAd/sacrifice-shrek.gif)

**Comment by senseiwells** [comment]
This has now been implemented, you can download the latest version on modrinth: https://modrinth.com/mod/server-replay/version/1.1.5+mc1.21.1

**Comment by HoldYourWaffle** [comment]
Wow that was quick, thanks again!
