### ISSUE TITLE
`/replay view` dosn't work on the latest 1.20.1 mod version

### ISSUE THREAD

**Issue by TriibuNupsik** [senseiwells/ServerReplay#67]
When using the latest version of the mod available on 1.20.1 it has the issue https://github.com/senseiwells/ServerReplay/issues/48
Could this be fixed, or is 1.20.1 deprecated?

Minecraft - 1.20.1
Server Replay - 1.1.1

**Comment by senseiwells** [comment]
The 1.20.1 version is no longer supported
