### ISSUE TITLE
1.21 support

### ISSUE THREAD

**Issue by ghost** [senseiwells/ServerReplay#69]
Just a reminder thought this mod was super cool though

**Comment by senseiwells** [comment]
1.21 has been supported for months now: https://modrinth.com/mod/server-replay/version/1.1.5+mc1.21.1

**Comment by ghost** [comment]
> 1.21 has been supported for months now: https://modrinth.com/mod/server-replay/version/1.1.5+mc1.21.1

I see it now, would it work on 1.21.3?

**Comment by senseiwells** [comment]
No, 1.21.3 cannot be supported until replay mod releases for 1.21.3
