### ISSUE TITLE
Feature Request: Simple Voice Chat recording

### ISSUE THREAD

**Issue by malloryhayr** [senseiwells/ServerReplay#9]
Not sure how possible this is, but it'd be nice to have a serverside implementation of https://github.com/henkelmax/replay-voice-chat

An example use case would be a UHC using Simple Voice Chat that wants to be able to just do one massive Replay recording without having everyone install Replay Mod with Replay Voice Chat.

For static area recording, it could only record non-group audio, but for individual player recording there could be an option to record that player's group's audio.

I'll probably explore this myself if nobody else gets around to doing it before this summer but I'm busy at the moment so I thought I'd share.

**Comment by senseiwells** [comment]
It seems very possible. I have (almost) finished implementing it, see the branch [here](https://github.com/senseiwells/ServerReplay/tree/voicechat). 
There are some issues currently with the audio getting distorted and I can't seem to figure out exactly why... So I'm probably going to leave it here for now until I have enough time to properly debug it, or until someone more familiar with the voice chat mod tells me what I've done wrong lol.

**Comment by senseiwells** [comment]
I believe I have now fixed this issue, was related to simple voice chat events being broadcasted off-thread.
I will do some more testing then this will be merged and released.

For now, you can try the working version [here](https://filebin.net/rxlccrsr6r2jcxhm/ServerReplay-1.0.7_mc1.20.4.jar)!

**Comment by senseiwells** [comment]
This has been merged

**Comment by malloryhayr** [comment]
Your work is amazing!! Thanks for implementing this :)
